import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import "../sass/globals.scss";
import {LocaleProvider} from "@/context/locale";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <LocaleProvider>
        <Header />
        <main>
          {children}
        </main>
      </LocaleProvider>
      </body>
    </html>
  );
}
